### ISSUE TITLE
Unable to build source; dependencies missing 

### ISSUE THREAD

**Issue by bsnyder** [jmesnil/jmx-js#1]
My first attempt to compile the source using Java 1.6 resulted in this: 

$ ant clean jar
Buildfile: build.xml

clean:
   [delete] Deleting directory /Users/bsnyder/src/jmx-js/build

compile:
    [mkdir] Created dir: /Users/bsnyder/src/jmx-js/build/classes
    [javac] Compiling 3 source files to /Users/bsnyder/src/jmx-js/build/classes
    [javac] javac: invalid source release: 1.6
    [javac] Usage: javac <options> <source files>
    [javac] where possible options include:
    [javac]   -g                         Generate all debugging info
    [javac]   -g:none                    Generate no debugging info
    [javac]   -g:{lines,vars,source}     Generate only some debugging info
    [javac]   -nowarn                    Generate no warnings
    [javac]   -verbose                   Output messages about what the compiler is doing
    [javac]   -deprecation               Output source locations where deprecated APIs are used
    [javac]   -classpath <path>          Specify where to find user class files
    [javac]   -cp <path>                 Specify where to find user class files
    [javac]   -sourcepath <path>         Specify where to find input source files
    [javac]   -bootclasspath <path>      Override location of bootstrap class files
    [javac]   -extdirs <dirs>            Override location of installed extensions
    [javac]   -endorseddirs <dirs>       Override location of endorsed standards path
    [javac]   -d <directory>             Specify where to place generated class files
    [javac]   -encoding <encoding>       Specify character encoding used by source files
    [javac]   -source <release>          Provide source compatibility with specified release
    [javac]   -target <release>          Generate class files for specific VM version
    [javac]   -version                   Version information
    [javac]   -help                      Print a synopsis of standard options
    [javac]   -X                         Print a synopsis of nonstandard options
    [javac]   -J<flag>                   Pass <flag> directly to the runtime system
    [javac] 

BUILD FAILED
/Users/bsnyder/src/jmx-js/build.xml:21: Compile failed; see the compiler error output for details.

Total time: 0 seconds

To get past this I removed the source="1.6" attribute. Unfortunately, this only uncovered further issues with compilation: 

$ ant clean jar
Buildfile: build.xml

clean:
   [delete] Deleting directory /Users/bsnyder/src/jmx-js/build

compile:
    [mkdir] Created dir: /Users/bsnyder/src/jmx-js/build/classes
    [javac] Compiling 3 source files to /Users/bsnyder/src/jmx-js/build/classes
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/Main.java:26: package javax.script does not exist
    [javac] import javax.script.ScriptEngine;
    [javac]                     ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/Main.java:27: package javax.script does not exist
    [javac] import javax.script.ScriptEngineManager;
    [javac]                     ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:20: package org.mozilla.javascript does not exist
    [javac] import static org.mozilla.javascript.Context.getUndefinedValue;
    [javac]                                      ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:20: static import only from classes and interfaces
    [javac] import static org.mozilla.javascript.Context.getUndefinedValue;
    [javac] ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:21: package org.mozilla.javascript does not exist
    [javac] import static org.mozilla.javascript.Context.jsToJava;
    [javac]                                      ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:21: static import only from classes and interfaces
    [javac] import static org.mozilla.javascript.Context.jsToJava;
    [javac] ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:33: package org.mozilla.javascript does not exist
    [javac] import org.mozilla.javascript.Context;
    [javac]                               ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:34: package org.mozilla.javascript does not exist
    [javac] import org.mozilla.javascript.FunctionObject;
    [javac]                               ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:35: package org.mozilla.javascript does not exist
    [javac] import org.mozilla.javascript.ScriptRuntime;
    [javac]                               ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:36: package org.mozilla.javascript does not exist
    [javac] import org.mozilla.javascript.Scriptable;
    [javac]                               ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:37: package org.mozilla.javascript does not exist
    [javac] import org.mozilla.javascript.ScriptableObject;
    [javac]                               ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:39: cannot find symbol
    [javac] symbol: class ScriptableObject
    [javac] public class ScriptableMBean extends ScriptableObject {
    [javac]                                      ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:98: cannot find symbol
    [javac] symbol  : class Scriptable
    [javac] location: class net.jmesnil.jmx.ScriptableMBean
    [javac]     public boolean has(String name, Scriptable arg1) {
    [javac]                                         ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:106: cannot find symbol
    [javac] symbol  : class Scriptable
    [javac] location: class net.jmesnil.jmx.ScriptableMBean
    [javac]     public Object get(String name, Scriptable arg1) {
    [javac]                                        ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:123: cannot find symbol
    [javac] symbol  : class Scriptable
    [javac] location: class net.jmesnil.jmx.ScriptableMBean
    [javac]     public void put(String name, Scriptable arg1, Object value) {
    [javac]                                      ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBeanServerConnection.java:23: package org.mozilla.javascript does not exist
    [javac] import org.mozilla.javascript.Context;
    [javac]                               ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBeanServerConnection.java:24: package org.mozilla.javascript does not exist
    [javac] import org.mozilla.javascript.NativeJavaArray;
    [javac]                               ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBeanServerConnection.java:25: package org.mozilla.javascript does not exist
    [javac] import org.mozilla.javascript.ScriptRuntime;
    [javac]                               ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBeanServerConnection.java:29: cannot find symbol
    [javac] symbol  : class Context
    [javac] location: class net.jmesnil.jmx.ScriptableMBeanServerConnection
    [javac]     private Context ctx;
    [javac]                 ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBeanServerConnection.java:44: cannot find symbol
    [javac] symbol  : class NativeJavaArray
    [javac] location: class net.jmesnil.jmx.ScriptableMBeanServerConnection
    [javac]     public NativeJavaArray getMBeans(String objectNameFilterStr) throws Exception {
    [javac]                ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/Main.java:34: cannot find symbol
    [javac] symbol  : class ScriptEngineManager
    [javac] location: class net.jmesnil.jmx.Main
    [javac]             ScriptEngineManager factory = new ScriptEngineManager();
    [javac]                 ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/Main.java:34: cannot find symbol
    [javac] symbol  : class ScriptEngineManager
    [javac] location: class net.jmesnil.jmx.Main
    [javac]             ScriptEngineManager factory = new ScriptEngineManager();
    [javac]                                                   ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/Main.java:35: cannot find symbol
    [javac] symbol  : class ScriptEngine
    [javac] location: class net.jmesnil.jmx.Main
    [javac]             ScriptEngine engine = factory.getEngineByName("js");
    [javac]                 ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:70: cannot find symbol
    [javac] symbol  : class FunctionObject
    [javac] location: class net.jmesnil.jmx.ScriptableMBean
    [javac]                     FunctionObject func = new FunctionObject(opInfo.getName(), this
    [javac]                         ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:70: cannot find symbol
    [javac] symbol  : class FunctionObject
    [javac] location: class net.jmesnil.jmx.ScriptableMBean
    [javac]                     FunctionObject func = new FunctionObject(opInfo.getName(), this
    [javac]                                                   ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:70: cannot find symbol
    [javac] symbol  : method getClass()
    [javac] location: class net.jmesnil.jmx.ScriptableMBean
    [javac]                     FunctionObject func = new FunctionObject(opInfo.getName(), this
    [javac]                                                                                    ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:93: method does not override a method from its superclass
    [javac]     @Override
    [javac]          ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:102: cannot find symbol
    [javac] symbol  : variable super
    [javac] location: class net.jmesnil.jmx.ScriptableMBean
    [javac]                     return super.has(name, arg1);
    [javac]                                ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:109: cannot find symbol
    [javac] symbol  : class Context
    [javac] location: class net.jmesnil.jmx.ScriptableMBean
    [javac]                             Context context = Context.getCurrentContext();
    [javac]                                 ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:109: cannot find symbol
    [javac] symbol  : variable Context
    [javac] location: class net.jmesnil.jmx.ScriptableMBean
    [javac]                             Context context = Context.getCurrentContext();
    [javac]                                                   ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:110: cannot find symbol
    [javac] symbol  : class Scriptable
    [javac] location: class net.jmesnil.jmx.ScriptableMBean
    [javac]                             Scriptable scope = ScriptRuntime.getTopCallScope(context);
    [javac]                                 ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:110: cannot find symbol
    [javac] symbol  : variable ScriptRuntime
    [javac] location: class net.jmesnil.jmx.ScriptableMBean
    [javac]                             Scriptable scope = ScriptRuntime.getTopCallScope(context);
    [javac]                                                    ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:116: cannot find symbol
    [javac] symbol  : method getUndefinedValue()
    [javac] location: class net.jmesnil.jmx.ScriptableMBean
    [javac]                             return getUndefinedValue();
    [javac]                                        ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:119: cannot find symbol
    [javac] symbol  : variable super
    [javac] location: class net.jmesnil.jmx.ScriptableMBean
    [javac]                     return super.get(name, arg1);
    [javac]                                ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBean.java:132: cannot find symbol
    [javac] symbol  : variable super
    [javac] location: class net.jmesnil.jmx.ScriptableMBean
    [javac]                     super.put(name, arg1, value);
    [javac]                         ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBeanServerConnection.java:52: cannot find symbol
    [javac] symbol  : variable Context
    [javac] location: class net.jmesnil.jmx.ScriptableMBeanServerConnection
    [javac]             return NativeJavaArray.wrap(ScriptRuntime.getTopCallScope(Context.getCurrentContext()), mbeans);
    [javac]                                                                           ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBeanServerConnection.java:52: cannot find symbol
    [javac] symbol  : variable ScriptRuntime
    [javac] location: class net.jmesnil.jmx.ScriptableMBeanServerConnection
    [javac]             return NativeJavaArray.wrap(ScriptRuntime.getTopCallScope(Context.getCurrentContext()), mbeans);
    [javac]                                             ^
    [javac] /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBeanServerConnection.java:52: cannot find symbol
    [javac] symbol  : variable NativeJavaArray
    [javac] location: class net.jmesnil.jmx.ScriptableMBeanServerConnection
    [javac]             return NativeJavaArray.wrap(ScriptRuntime.getTopCallScope(Context.getCurrentContext()), mbeans);
    [javac]                        ^
    [javac] Note: /Users/bsnyder/src/jmx-js/src/net/jmesnil/jmx/ScriptableMBeanServerConnection.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 38 errors

BUILD FAILED
/Users/bsnyder/src/jmx-js/build.xml:21: Compile failed; see the compiler error output for details.

Total time: 7 seconds

It seems as if the whole project may not be checked in here. Notice that the following file seems to be incomplete: 

http://github.com/jmesnil/jmx-js/blob/master/src/net/jmesnil/jmx/ScriptableMBeanServerConnection.java

Upon cloning the repo, this class appears all jumbled and crammed together. Replacing all the ^M characters fixes this. 

And where are the missing dependencies (e.g., javax.script, org.mozilla.javascript, etc.)? 

Bruce

**Comment by jmesnil** [comment]
hi bruce,

I fixed the build (fyi I'm using Java 6 on Mac OS X) and the ScriptableMBeanServerConnection.java class.
I've also added instructions to install the dependencies to the README file.

However, running the examples, it intermittently fails with Rhino giving me an "undefined" object instead of a ScriptableMBean object. I'll try to fix it in the coming days.

Thanks for the report

**Comment by bsnyder** [comment]
Thanks for the info, Jeff. Unfortunately, even after dropping those two jars into the lib/ext dir I'm still stuck with the same compilation failures. I'm also using Java 1.6 on Mac OS X and I can't find a jar containing the javax.script.ScriptEngine object anywhere. Am I just overlooking something? 

Bruce

**Comment by jmesnil** [comment]
mmhh, that's weird: the javax.script package is
standard in Java 6 (http://java.sun.com/javase/6/docs/api/javax/script/ScriptEngine.html).
In Mac OS X, it is in classes.jar:

$ jar tvf /System/Library/Frameworks/JavaVM.framework/Versions/1.6/Classes/classes.jar | grep javax/script/ScriptEngine.class
  1440 Fri Nov 13 15:21:58 CET 2009 javax/script/ScriptEngine.class

**Comment by bsnyder** [comment]
I'm a fool - I didn't have the JAVA_HOME set so the build was unable to find the libraries. After setting the JAVA_HOME, the compilation succeeds. 

Thanks for your help, Jeff. 

Bruce

**Comment by jmesnil** [comment]
I do not need to set JAVA_HOME to have it work. 

tbh, I don't understand totally how Mac OS X manages the Java runtime (with their Current & A symlinks)...
After reading yoiur blog, I wonder if your env may have a missing link after using setjdk?

anyway, at least it works for you now :)

**Comment by bsnyder** [comment]
Yeah, it's quite possible that setjdk may not be setting all the necessary symlinks in Snow Leopard. In fact, I've avoided installing the latest Java update (after peeking inside it with the Pacifist and seeing what it will do) until I've got more time to dissect it. Anyway, it works for now ;-). 

Bruce
